/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

type RegistryItemWithComponent = RegistryItem & {
  component: React.LazyExoticComponent<React.ComponentType<any>>;
};

export const Index: Record<string, RegistryItemWithComponent> = {
  chip: {
    name: "chip",
    type: "registry:ui",
    title: "Chip",
    description:
      "A component that combines small text with an icon for quick callouts. This component highlights key values such as benefits, attributes, or job details.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/ui/chip.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/chip.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "featured-icon": {
    name: "featured-icon",
    type: "registry:ui",
    title: "Featured Icon",
    description:
      "A component that places an icon inside a styled square or circle frame for extra prominence. This component makes supporting visuals stand out in marketing layouts.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/ui/featured-icon.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/featured-icon.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  heading: {
    name: "heading",
    type: "registry:ui",
    title: "Heading",
    description: "Pending",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/ui/heading.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/heading.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card": {
    name: "profile-card",
    type: "registry:ui",
    title: "Profile Card",
    description:
      "An extension of the avatar component with more details on the individual. Good for blog posts etc.",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "src/registry/pro-marketing/ui/profile-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/profile-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating": {
    name: "star-rating",
    type: "registry:ui",
    title: "Star Rating",
    description:
      "A component that displays ratings with stars and an optional label. This component builds trust with visual feedback.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/ui/star-rating.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/star-rating.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "ui-showcase": {
    name: "ui-showcase",
    type: "registry:ui",
    title: "UI Showcase",
    description:
      "A Placeholder that displays content in a device-style frame. This component helps showcase product UI.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/ui/ui-showcase.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/ui/ui-showcase.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "blog-blockquote": {
    name: "blog-blockquote",
    type: "registry:component",
    title: "Blog Blockquote",
    description: "TBC",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/profile-card.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/blog-blockquote.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/blog-blockquote.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "blog-image": {
    name: "blog-image",
    type: "registry:component",
    title: "Blog Image",
    description:
      "A component that displays an inline or full-width image with an optional caption. This component makes blog articles more engaging and visually appealing.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/components/blog-image.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/blog-image.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "feature-stack": {
    name: "feature-stack",
    type: "registry:component",
    title: "Feature Stack",
    description:
      "A component that arranges an icon, header, body text, and CTA in different layout styles. This component makes features clear and actionable.",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/featured-icon.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/feature-stack.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/feature-stack.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "job-listing": {
    name: "job-listing",
    type: "registry:component",
    title: "Job Listing",
    description:
      "A component that displays open roles in a card format with a badge, title, short body, and feature chips. This component brings structure and clarity to careers pages.",
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/registry/pro-marketing/components/job-listing.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/job-listing.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  metric: {
    name: "metric",
    type: "registry:component",
    title: "Metric",
    description:
      "A component that displays large stats with a sub-label for context. This component is designed to highlight performance or usage data.",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/pro-marketing/components/metric.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/metric.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "pricing-card": {
    name: "pricing-card",
    type: "registry:component",
    title: "Pricing Card",
    description:
      "A component for Figma that compares plans with layout variants, including a “Most Popular” highlight. This component makes pricing clear and actionable.",
    registryDependencies: ["badge", "button"],
    files: [
      {
        path: "src/registry/pro-marketing/components/pricing-card.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/pricing-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading": {
    name: "section-heading",
    type: "registry:component",
    title: "Section Heading",
    description:
      "A component that standardises heading typography and spacing. This component includes a pre-heading label, main heading, and body text in different layout variants.",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/components/section-heading.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/section-heading.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "sub-feature": {
    name: "sub-feature",
    type: "registry:component",
    title: "Sub Feature",
    description:
      "A component that presents a smaller feature layout for a dialled-back look. This component balances detail with simplicity.",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/pro-marketing/components/sub-feature.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/components/sub-feature.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "blog-blockquote-example": {
    name: "blog-blockquote-example",
    type: "registry:example",
    title: "Blog Blockquote Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/blog-blockquote.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/blog-blockquote-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/blog-blockquote-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "blog-image-example": {
    name: "blog-image-example",
    type: "registry:example",
    title: "Blog Image Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/blog-image.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/blog-image-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/blog-image-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "chip-example": {
    name: "chip-example",
    type: "registry:example",
    title: "Chip Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/chip.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/chip-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/chip-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "feature-stack-example": {
    name: "feature-stack-example",
    type: "registry:example",
    title: "Feature Stack Example",
    description: "",
    registryDependencies: ["button", "https://shadcraft-registry.vercel.app/r/feature-stack.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/feature-stack-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/feature-stack-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "featured-icon-example": {
    name: "featured-icon-example",
    type: "registry:example",
    title: "Featured Icon Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/featured-icon.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/featured-icon-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/featured-icon-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "heading-example": {
    name: "heading-example",
    type: "registry:example",
    title: "Heading Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/heading-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/heading-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "job-listing-example": {
    name: "job-listing-example",
    type: "registry:example",
    title: "Job Listing Example",
    description: "",
    registryDependencies: [
      "button",
      "https://shadcraft-registry.vercel.app/r/job-listing.json",
      "https://shadcraft-registry.vercel.app/r/chip.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/examples/job-listing-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/job-listing-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "metric-example": {
    name: "metric-example",
    type: "registry:example",
    title: "Metric Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/metric.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/metric-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/metric-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "pricing-card-example": {
    name: "pricing-card-example",
    type: "registry:example",
    title: "Pricing Card Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/pricing-card.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/pricing-card-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/pricing-card-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "profile-card-example": {
    name: "profile-card-example",
    type: "registry:example",
    title: "Profile Card Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/profile-card.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/profile-card-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/profile-card-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "section-heading-example": {
    name: "section-heading-example",
    type: "registry:example",
    title: "Section Heading Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/section-heading.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/section-heading-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/section-heading-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "star-rating-example": {
    name: "star-rating-example",
    type: "registry:example",
    title: "Star Rating Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/star-rating.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/star-rating-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/star-rating-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "sub-feature-example": {
    name: "sub-feature-example",
    type: "registry:example",
    title: "Sub Feature Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/sub-feature.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/sub-feature-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/sub-feature-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "ui-showcase-example": {
    name: "ui-showcase-example",
    type: "registry:example",
    title: "UI Showcase Example",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/ui-showcase.json"],
    files: [
      {
        path: "src/registry/pro-marketing/examples/ui-showcase-example.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/examples/ui-showcase-example.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: { bundle: "pro-marketing" },
  },
  "banner-1": {
    name: "banner-1",
    type: "registry:block",
    title: "Banner 1",
    description: "",
    registryDependencies: [
      "button",
      "input",
      "https://shadcraft-registry.vercel.app/r/featured-icon.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/banner-1/components/banner-1.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/banner-1/components/banner-1.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["banners"],
    meta: { bundle: "pro-marketing", containerClassName: "absolute inset-x-0 top-0 p-4" },
  },
  "banner-2": {
    name: "banner-2",
    type: "registry:block",
    title: "Banner 2",
    description: "",
    registryDependencies: ["button", "https://shadcraft-registry.vercel.app/r/featured-icon.json"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/banner-2/components/banner-2.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/banner-2/components/banner-2.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["banners"],
    meta: { bundle: "pro-marketing", containerClassName: "absolute inset-x-0 top-0 p-4" },
  },
  "banner-3": {
    name: "banner-3",
    type: "registry:block",
    title: "Banner 3",
    description: "",
    registryDependencies: ["button", "https://shadcraft-registry.vercel.app/r/featured-icon.json"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/banner-3/components/banner-3.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/banner-3/components/banner-3.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["banners"],
    meta: { bundle: "pro-marketing", containerClassName: "absolute inset-x-0 top-0 p-4" },
  },
  "banner-4": {
    name: "banner-4",
    type: "registry:block",
    title: "Banner 4",
    description: "",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/banner-4/components/banner-4.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/banner-4/components/banner-4.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["banners"],
    meta: { bundle: "pro-marketing", containerClassName: "absolute inset-x-0 top-0 p-4" },
  },
  "careers-1": {
    name: "careers-1",
    type: "registry:block",
    title: "Careers 1",
    description: "",
    registryDependencies: [
      "button",
      "separator",
      "https://shadcraft-registry.vercel.app/r/job-listing.json",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/chip.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/careers-1/page.tsx",
        type: "registry:page",
        target: "app/careers/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/careers-1/components/careers-1.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/careers-1/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["careers"],
    meta: { bundle: "pro-marketing" },
  },
  "careers-2": {
    name: "careers-2",
    type: "registry:block",
    title: "Careers 2",
    description: "",
    registryDependencies: [
      "button",
      "separator",
      "https://shadcraft-registry.vercel.app/r/job-listing.json",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/chip.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/careers-2/page.tsx",
        type: "registry:page",
        target: "app/careers/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/careers-2/components/careers-2.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/careers-2/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["careers"],
    meta: { bundle: "pro-marketing" },
  },
  "careers-3": {
    name: "careers-3",
    type: "registry:block",
    title: "Careers 3",
    description: "",
    registryDependencies: [
      "button",
      "https://shadcraft-registry.vercel.app/r/job-listing.json",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/chip.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/careers-3/page.tsx",
        type: "registry:page",
        target: "app/careers/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/careers-3/components/careers-3.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/careers-3/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["careers"],
    meta: { bundle: "pro-marketing" },
  },
  "careers-4": {
    name: "careers-4",
    type: "registry:block",
    title: "Careers 4",
    description: "",
    registryDependencies: [
      "button",
      "separator",
      "https://shadcraft-registry.vercel.app/r/job-listing.json",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/chip.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/careers-4/page.tsx",
        type: "registry:page",
        target: "app/careers/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/careers-4/components/careers-4.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/careers-4/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["careers"],
    meta: { bundle: "pro-marketing" },
  },
  "footer-1": {
    name: "footer-1",
    type: "registry:block",
    title: "Footer 1",
    description: "",
    registryDependencies: ["badge", "separator"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/footer-1/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/footer-1/components/footer.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/footer-1/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["footers"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-1": {
    name: "contact-1",
    type: "registry:block",
    title: "Contact 1",
    description: "",
    registryDependencies: [
      "button",
      "input",
      "textarea",
      "checkbox",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-1/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-1/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-2": {
    name: "contact-2",
    type: "registry:block",
    title: "Contact 2",
    description: "",
    registryDependencies: [
      "button",
      "input",
      "textarea",
      "checkbox",
      "card",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-2/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-2/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-3": {
    name: "contact-3",
    type: "registry:block",
    title: "Contact 3",
    description: "",
    registryDependencies: [
      "button",
      "input",
      "textarea",
      "checkbox",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-3/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-3/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-4": {
    name: "contact-4",
    type: "registry:block",
    title: "Contact 4",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
      "https://shadcraft-registry.vercel.app/r/featured-icon.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-4/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-4/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-5": {
    name: "contact-5",
    type: "registry:block",
    title: "Contact 5",
    description: "",
    registryDependencies: [
      "popover",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-5/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-5/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-6": {
    name: "contact-6",
    type: "registry:block",
    title: "Contact 6",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-6/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
      {
        path: "src/registry/pro-marketing/blocks/contact-6/components/map.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-6/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-7": {
    name: "contact-7",
    type: "registry:block",
    title: "Contact 7",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-7/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-7/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-8": {
    name: "contact-8",
    type: "registry:block",
    title: "Contact 8",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-8/contact-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/contact-8/contact-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing" },
  },
  "contact-9": {
    name: "contact-9",
    type: "registry:block",
    title: "Contact 9",
    description: "",
    registryDependencies: [
      "button",
      "avatar",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/contact-9/components/contact-9.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/pro-marketing/blocks/contact-9/components/contact-9.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["contact"],
    meta: { bundle: "pro-marketing", containerClassName: "px-5 py-12 lg:p-20" },
  },
  "faqs-1": {
    name: "faqs-1",
    type: "registry:block",
    title: "FAQs 1",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/feature-stack.json",
      "https://shadcraft-registry.vercel.app/r/featured-icon.json",
      "https://shadcraft-registry.vercel.app/r/contact-9.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/faqs-1/page.tsx",
        type: "registry:page",
        target: "app/faqs/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/faqs-1/components/faqs-1.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/faqs-1/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["faqs"],
    meta: { bundle: "pro-marketing" },
  },
  "faqs-2": {
    name: "faqs-2",
    type: "registry:block",
    title: "FAQs 2",
    description: "",
    registryDependencies: [
      "accordion",
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/contact-9.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/faqs-2/page.tsx",
        type: "registry:page",
        target: "app/faqs/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/faqs-2/components/faqs-2.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/faqs-2/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["faqs"],
    meta: { bundle: "pro-marketing" },
  },
  "footer-2": {
    name: "footer-2",
    type: "registry:block",
    title: "Footer 2",
    description: "",
    registryDependencies: ["input", "button", "badge", "separator"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/footer-2/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/footer-2/components/footer.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/footer-2/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["footers"],
    meta: { bundle: "pro-marketing" },
  },
  "footer-3": {
    name: "footer-3",
    type: "registry:block",
    title: "Footer 3",
    description: "",
    registryDependencies: ["separator"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/footer-3/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/footer-3/components/footer.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/footer-3/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["footers"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-1": {
    name: "metrics-1",
    type: "registry:block",
    title: "Metrics 1",
    description: "",
    registryDependencies: ["https://shadcraft-registry.vercel.app/r/metric.json"],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-1/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-1/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-1/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-2": {
    name: "metrics-2",
    type: "registry:block",
    title: "Metrics 2",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-2/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-2/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-2/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-3": {
    name: "metrics-3",
    type: "registry:block",
    title: "Metrics 3",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-3/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-3/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-3/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-4": {
    name: "metrics-4",
    type: "registry:block",
    title: "Metrics 4",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-4/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-4/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-4/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-5": {
    name: "metrics-5",
    type: "registry:block",
    title: "Metrics 5",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-5/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-5/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-5/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-6": {
    name: "metrics-6",
    type: "registry:block",
    title: "Metrics 6",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-6/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-6/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-6/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
  "metrics-7": {
    name: "metrics-7",
    type: "registry:block",
    title: "Metrics 7",
    description: "",
    registryDependencies: [
      "https://shadcraft-registry.vercel.app/r/section-heading.json",
      "https://shadcraft-registry.vercel.app/r/metric.json",
    ],
    files: [
      {
        path: "src/registry/pro-marketing/blocks/metrics-7/page.tsx",
        type: "registry:page",
        target: "app/metrics/page.tsx",
      },
      {
        path: "src/registry/pro-marketing/blocks/metrics-7/components/metrics-section.tsx",
        type: "registry:component",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/pro-marketing/blocks/metrics-7/page.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["metrics"],
    meta: { bundle: "pro-marketing" },
  },
};
